### ISSUE TITLE
Indexing selected fields only

### ISSUE THREAD

**Issue by HirenBhalani-BTC** [liberation/django-elasticsearch#10]
How to configure subset of fields to be index at model level?

I have User model with user_name, email and password. I configured fields like below snapshot but I am still able to search the term mentioned in the email address and password. 

```
class User(EsIndexable, models.Model):
	user_name = models.CharField(max_length=25)
	email = models.CharField(max_length=50)
	password = models.CharField(max_length=25)
class Elasticsearch(EsIndexable.Elasticsearch):
    mappings = {'user_name': {'boost': 2.0, 'analyzer': 'autocomplete'} }
    fields = ['user_name']
```

I don't want to index email and password. How can I configure model and what other steps required to achieve this?

**Comment by lauxley** [comment]
Hi, it should work as you describe,
but since the test ```EsIndexableTestCase.test_custom_fields``` is still passing, I doubt it is a bug, is the Elasticsearch Class inside the User class ? it should look like this:
```python
class User(EsIndexable, models.Model):
    user_name = models.CharField(max_length=25)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=25)

    class Elasticsearch(EsIndexable.Elasticsearch):
        mappings = {'user_name': {'boost': 2.0, 'analyzer': 'autocomplete'} }
        fields = ['user_name']
```

On a side note, you really should not store the password as a CharField, or even handle that kind of stuff yourself, look up django.contrib.auth, this app should do everything you need. If you do, you can make a proxy class to make it indexable by django-elasticsearch.

I'll keep that ticket open for now but you should consider asking help on irc #django @freenode, or on reddit www.reddit.com/r/django for general django/python problems.

**Comment by HirenBhalani-BTC** [comment]
My problem is solved,
Thank you.
