### ISSUE TITLE
Highlight option

### ISSUE THREAD

**Issue by Nbooo** [liberation/django-elasticsearch#21]
Hi there! Excuse me if the question is dumb, I'm very new to elasticsearch and django. In docs for Elasticsearch I can see the "highlight" option to mark the words in document that matched to my query. Is it possible through django-elasticsearch? Thanks in advance!

**Comment by lauxley** [comment]
Hi,
short answer is no. 
However there is an ```extra_body``` parameter in the EsQueryset that was added in the first place to allow to do this kind of things. It's not implemented yet because i am unsure how to map the results for an arbitrary query - for example the 'completion' *add* to the search results while highlighting *change* it's content. I could just allow it and let the user deal with the results in ```q._response```, it wouldn't feel right but it would be better than nothing i guess.

**Comment by lauxley** [comment]
You can now use the .extra() method to do this, there is an example of it [here](https://github.com/liberation/django-elasticsearch/blob/master/django_elasticsearch/tests/test_qs.py#L344).

I'm letting the issue opened since it may make sense to have a ```.highligh(field)``` method.

**Comment by Nbooo** [comment]
Thank's for the answer. I already cloned the repo and modified the source the way I need, however the "extra" option is much better. Thanks, I'll try it!
