### ISSUE TITLE
Autocomplete example

### ISSUE THREAD

**Issue by codingwithoutcomments** [liberation/django-elasticsearch#24]
Can you provide an example for autocomplete?

Here's my model:

```
class Article(EsIndexable, BaseContent):
    title = models.CharField(max_length=200, unique=False, blank=True, null=True)
    content = models.TextField(db_column="text", blank=True, null=True)

    class Elasticsearch(EsIndexable.Elasticsearch):
        completion_fields = ['title', 'content']
```

But then when i run:
```
Article.es.complete('title', 'test')
```

I get a 

```
TransportError: TransportError(500, u'{"_shards":{"total":5,"successful":0,"failed":5,"failures":[{"index":"django","shard":0,"status":500,"reason":"BroadcastShardOperationFailedException[[[django][0] ]; nested: ElasticsearchException[failed to execute suggest]
```

**Comment by lauxley** [comment]
Hi,
you can see an example in the [tests](https://github.com/liberation/django-elasticsearch/blob/master/django_elasticsearch/tests/test_indexable.py#L123). My guess about your problem is that the elasticsearch mapping is not synced with the model and thus does not contain informations about the fields use for suggestions/autocompletion, you should see 2 fields with ``type: completion`` when you do ``Article.es.get_mapping()``.
You can flush the model as i do in the test or manually change elasticsearch's mapping if you don't want to lose your datas.
