### ISSUE TITLE
[Question] Could you tell me wich version of ElasticSearch is involved ?

### ISSUE THREAD

**Issue by NicolasYDDER** [liberation/django-elasticsearch#4]
Hi liberation team,

I'm very interesting by your lib but, in your readme.md, I did'nt find information about the ES version compatibility ?

Could you let me know ?

Best Regards,

Nicolas.

**Comment by lauxley** [comment]
Hi, thank you for pointing this out, I’ll update the readme.

As stated in the python elasticsearch lib documentation:
```
There are two branches for development - master and 0.4. Master branch is used to track all the changes for Elasticsearch 1.0 and beyond whereas 0.4 tracks Elasticsearch 0.90.

Releases with major version 1 (1.X.Y) are to be used with Elasticsearch 1.* and later, 0.4 releases are meant to work with Elasticsearch 0.90.*.
```
So, to answer your question, it depends on which version of this library you install.
We personally use Elasticsearch 1.3.9 and the corresponding 1.2.0 python module, but I'm rather confident that it should work fine with older versions of Elasticsearch since the API didn't change much from what i can gather in the [changelogs](http://elasticsearch-py.readthedocs.org/en/master/Changelog.html).

I'm not quite sure if i should bother testing for older versions of Elasticsearch <0.9, maybe a fork would be the way to go.

**Comment by NicolasYDDER** [comment]
Hi lauxley,

Thanks for your reactivity. It's clear. I'm trying it ;)

Question out of the scope: I already create an index and some doctypes in ES, How can I match my models with each docTypes.
Is the binding  done with the class name model ?

 BR

Nicolas.

**Comment by lauxley** [comment]
If i understand your question correctly, you can override the ```doc_type```  property or the ```get_doc_type``` method of the ElasticSearchManager, but it's not easily done, you need to instantiate your own subclass of the manager.
I should probably allow to set it easily just like the index. I'll open a new issue for this, if you have any other, please open another ticket as i'll leave this one open until i update the docs.
